services:
    acme_user.password_resetting:
        class: SimpleUserBundle\EventListener\PasswordResettingListener
        arguments: ['@router']
        tags:
            - { name: kernel.event_subscriber }