app:
    resource: "@AppBundle/Controller/"
    type:     annotation

admin_boroughs_services:
    resource: "@BoroughServicesBundle/Controller/"
    prefix:   /admin/services
    type:     annotation

lexik_translation_edition:
    resource: "@LexikTranslationBundle/Resources/config/routing.yml"
    prefix:   /admin/translations

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting